import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import MainHeader from '@/components/MainHeader';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col">
        <div className="flex min-h-screen flex-col items-center bg-zinc-50 font-sans bg-linear-to-r from-cyan-500 to-blue-500 dark:bg-black">
          <MainHeader />
          <main className="flex w-full max-w-7xl flex-1 flex-col items-center justify-between py-16 px-16  bg-white dark:bg-black sm:items-start">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
